name: birthday_app
description: A simple flutter application to invite your friends to your party!

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_screenutil: ^5.8.4
  birthday_ui:
    path: packages/birthday_ui
  intl: ^0.18.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/images/

  fonts:
    - family: Jost
      fonts:
        - asset: assets/fonts/Jost-Italic-VariableFont_wght.ttf
        - asset: assets/fonts/Jost-VariableFont_wght.ttf
    - family: YesevaOne
      fonts:
        - asset: assets/fonts/YesevaOne-Regular.ttf
